on:
  watch:
    types: started
  push:
    tags: 
      - "v*"

name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with: 
         go-version: 1.15.x

      - name: Setup xcaddy
        run: |
          wget https://raw.githubusercontent.com/charlieethan/naive-build/master/src/xcaddy.sh && chmod +x xcaddy.sh && ./xcaddy.sh
          git clone -b naive https://github.com/klzgrad/forwardproxy

      - name: Create Release
        id: create_release
        uses: monkeyWie/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Build linux-amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          ./xcaddy build --output $PWD/caddy-linux-amd64 HEAD --with github.com/caddyserver/forwardproxy=$PWD/forwardproxy
          chmod +x caddy-linux-amd64
      - name: Release linux-amd64
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./caddy-linux-amd64
          asset_name: caddy-linux-amd64
          asset_content_type: application/zip
